import fs from 'node:fs';
import path from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

type LevelConfig = {
  code: string;
  title: string;
  description: string;
};

type LanguageConfig = {
  code: string;
  label: string;
  levels: LevelConfig[];
};

function getLessonItems(dirName: string) {
  const absoluteDir = path.join(process.cwd(), 'docs', dirName);
  const hasLessonFiles =
    fs.existsSync(absoluteDir) &&
    fs
      .readdirSync(absoluteDir)
      .some((fileName) => /\.(?:md|mdx)$/.test(fileName));

  return hasLessonFiles ? [{type: 'autogenerated' as const, dirName}] : [];
}

function createLevelItem(languageCode: string, level: LevelConfig) {
  const dirName = `${languageCode}/${level.code}`;
  const items = getLessonItems(dirName);

  if (items.length === 0) {
    return undefined;
  }

  return {
    type: 'category' as const,
    label: level.code.toUpperCase(),
    key: `${languageCode}-${level.code}`,
    link: {
      type: 'generated-index' as const,
      slug: `/${dirName}`,
      title: level.title,
      description: level.description,
    },
    items,
  };
}

function isDefined<T>(value: T | undefined): value is T {
  return value !== undefined;
}

function createLanguageItem(language: LanguageConfig) {
  const levelItems = language.levels
    .map((level) => createLevelItem(language.code, level))
    .filter(isDefined);

  if (levelItems.length === 0) {
    return `${language.code}/index`;
  }

  return {
    type: 'category' as const,
    label: language.label,
    link: {
      type: 'doc' as const,
      id: `${language.code}/index`,
    },
    items: levelItems,
  };
}

const languages: LanguageConfig[] = [
  {
    code: 'spa',
    label: 'Hiszpański',
    levels: [
      {
        code: 'b1',
        title: 'Hiszpański B1',
        description:
          'Lekcje hiszpańskiego na poziomie średnio zaawansowanym.',
      },
      {
        code: 'b2',
        title: 'Hiszpański B2',
        description:
          'Lekcje hiszpańskiego do omawiania niuansów i kompromisów.',
      },
    ],
  },
  {
    code: 'deu',
    label: 'Niemiecki',
    levels: [
      {
        code: 'b1',
        title: 'Niemiecki B1',
        description: 'Lekcje niemieckiego o codziennych planach i rutynach.',
      },
      {
        code: 'b2',
        title: 'Niemiecki B2',
        description:
          'Lekcje niemieckiego do budowania uporządkowanych argumentów.',
      },
    ],
  },
  {
    code: 'arb',
    label: 'Arabski',
    levels: [
      {
        code: 'a1',
        title: 'Arabski A1',
        description: 'Lekcje arabskiego dla osób zaczynających od podstaw.',
      },
      {
        code: 'a2',
        title: 'Arabski A2',
        description: 'Lekcje arabskiego do prostych codziennych sytuacji.',
      },
      {
        code: 'b1',
        title: 'Arabski B1',
        description: 'Lekcje arabskiego do samodzielnej komunikacji.',
      },
      {
        code: 'b2',
        title: 'Arabski B2',
        description: 'Lekcje arabskiego do wyjaśniania opinii i argumentów.',
      },
      {
        code: 'c1',
        title: 'Arabski C1',
        description: 'Lekcje arabskiego do swobodnej, precyzyjnej komunikacji.',
      },
      {
        code: 'c2',
        title: 'Arabski C2',
        description:
          'Lekcje arabskiego do zaawansowanej pracy z rejestrem i stylem.',
      },
    ],
  },
];

const sidebars: SidebarsConfig = {
  lessonsSidebar: languages.map(createLanguageItem),
};

export default sidebars;
