import fs from 'node:fs';
import path from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import {languages, type LanguageConfig, type LevelConfig} from './src/languages';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

function getLessonItems(dirName: string) {
  const absoluteDir = path.join(process.cwd(), 'docs', dirName);
  const hasLessonFiles =
    fs.existsSync(absoluteDir) &&
    fs
      .readdirSync(absoluteDir)
      .some((fileName) => /\.(?:md|mdx)$/.test(fileName));

  return hasLessonFiles ? [{type: 'autogenerated' as const, dirName}] : [];
}

function createLevelItem(languageCode: string, level: LevelConfig) {
  const dirName = `${languageCode}/${level.code}`;
  const items = getLessonItems(dirName);

  if (items.length === 0) {
    return undefined;
  }

  return {
    type: 'category' as const,
    label: level.code.toUpperCase(),
    key: `${languageCode}-${level.code}`,
    link: {
      type: 'generated-index' as const,
      slug: `/${dirName}`,
      title: level.title,
      description: level.description,
    },
    items,
  };
}

function isDefined<T>(value: T | undefined): value is T {
  return value !== undefined;
}

function createLanguageItem(language: LanguageConfig) {
  const levelItems = language.levels
    .map((level) => createLevelItem(language.code, level))
    .filter(isDefined);

  if (levelItems.length === 0) {
    return `${language.code}/index`;
  }

  return {
    type: 'category' as const,
    label: language.label,
    link: {
      type: 'doc' as const,
      id: `${language.code}/index`,
    },
    items: levelItems,
  };
}

const sidebars: SidebarsConfig = Object.fromEntries(
  languages.map((language) => [language.code, [createLanguageItem(language)]]),
);

export default sidebars;
